"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$git_branch$git_status$cmd_duration
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
format = "[$path]($style) "
style = "bold color_blue"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold color_green"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold color_orange"

[cmd_duration]
min_time = 2_000
format = "[ $duration]($style)"
style = "color_yellow"

[character]
success_symbol = "[❯](bold color_green)"
error_symbol = "[❯](bold color_red)"
vimcmd_symbol = "[❮](bold color_green)"
vimcmd_replace_one_symbol = "[❮](bold color_purple)"
vimcmd_replace_symbol = "[❮](bold color_purple)"
vimcmd_visual_symbol = "[❮](bold color_yellow)"
